server:
  port: 9002
  servlet:
    session:
      timeout: 1800
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  redis:
    host: 8.131.85.141
    port: 6379
    password: xyrssml123